### ISSUE TITLE
为什么项目启不起来了？

### ISSUE THREAD

**Issue by wo-de-ping-er** [ant-design/sunflower#13]
![image](https://user-images.githubusercontent.com/23158766/60261536-b2363680-990e-11e9-8c58-b08b43316b86.png)
报了这个错误

**Comment by JIACHENG9** [comment]
yarn bootstrap 没有？
要是还报错可能是 scrpts/docz-plugin-alias.js 对 windows 的路径没搞对，还没有在 windows 测试。

要是想试用也可在你的应用中使用


yarn add @sunflower-antd/form-table
or
npm install @sunflower-antd/form-table
、、、
