### ISSUE TITLE
useFormTable 和 useModalForm 怎么同时使用 antd@3

### ISSUE THREAD

**Issue by Nokecy** [ant-design/sunflower#69]
useModalForm 可以做一个表格操作的例子吗？类似https://ant.design/components/table-cn/#components-table-demo-jsx  包括添加、编辑

**Comment by JIACHENG9** [comment]
是可以的，只是还没有加到示例

**Comment by Nokecy** [comment]
@JIACHENG9  有时间可以加一个简单的示例吗？

**Comment by JIACHENG9** [comment]
@Nokecy 在考虑将脚手架一起提供到 sunflower github
