### ISSUE TITLE
typescript下useFormTable返回的tableProps和antd的Table类型不匹配

### ISSUE THREAD

**Issue by wyj580231** [ant-design/sunflower#71]
使用useFormTable返回的tableProps直接赋值给antd的Table组件报类型错误，应该是sun-flower导出的pagination=>current【StoreValue】类型和antd的number类型不兼容
![image](https://user-images.githubusercontent.com/30888500/69020800-bf081380-09f0-11ea-8b2e-e34807a3ec4e.png)

**Comment by Mr-zyy** [comment]
[已修复](https://github.com/ant-design/sunflower/commit/1acaf0bb63fe3d5f7591e34f0f8aff300af5a66e)，下个版本发布
